spring:
  mail:
    password: vghwrprtorppbrcy
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 8ea199693cc2ce1fcd18ed34d8b241d7
custom:
  tossPayments:
    widget:
      secretKey: test_sk_EP59LybZ8BvYYBx5J7Pn86GYo7pR

