spring:
  profiles:
    active: dev
    include: secret
  autoconfigure:
    exclude: # 레디스 디펜던시들이 로컬 환경에서 작동하지 않고 운영환경에서만 작동
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.session.SessionAutoConfiguration
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  threads:
    virtual:
      enabled: true
  mail: # 이메일 발송
    host: smtp.gmail.com
    port: 587
    username: tourdemonde2024@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  datasource:
    url: jdbc:h2:./TdM_dev;MODE=MYSQL # DB : TdM_dev
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: ON_SECRET
            scope: profile_nickname, profile_image
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: '${custom.site.baseUrl}/{action}/oauth2/code/{registrationId}'
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  thymeleaf:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
logging:
  level:
    com.ll.tourdemonde: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
custom:
  site:
    name: Tour-de-Monde
    baseUrl: "http://localhost:${server.port}"
  temp:
#    dirPath: c:/temp/TdM_dev/temp
      dirPath: /tmp/TdM_dev/temp # Mac 환경
  genFile:
#    dirPath: c:/temp/TdM_dev
      dirPath: /tmp/TdM_dev # Mac 환경
  tossPayments:
    widget:
      clientKey: test_ck_0RnYX2w532wDqZARKgegVNeyqApQ
      secretKey: ON_SECRET
  order:
    cancelableSeconds: 3600
